Clusters:
- Input:
    Kafka:
      Name: go2ch
      Brokers:
        - "172.16.186.16:19092"
      Topics:
        - hdLog
      Group: test
      Consumers: 16
  Filters:
    - Action: drop
      Conditions:
        - Key: k8s_container_name
          Value: "-rpc"
          Type: contains
        - Key: level
          Value: info
          Type: match
          Op: and
    - Action: remove_field
      Fields:
        - message
        - _source
        - _type
        - _score
        - _id
        - "@version"
        - topic
        - index
        - beat
        - docker_container
        - offset
        - prospector
        - source
        - stream
    - Action: transfer
      Field: message
      Target: data
  Output:
    ClickHouse:
      Addrs:
        - "172.16.141.4:9200"
      Username: "default"
      Password: ""
      Database: "default"
      TableName: "hdLog"
      DDL: ""
      DialTimeoutSecond: 5
      MaxIdleConns: 5
      MaxOpenConns: 10
      ConnMaxLiftTimeMinute: 60
      MaxChunkBytes: 10485760
      FlushIntervalSecond: 5